import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const MEAL_ORDER = [
  "breakfast",
  "mid_morning_snack",
  "lunch",
  "afternoon_snack",
  "dinner",
  "evening_snack",
];

const MEAL_LABELS: { [key: string]: string } = {
  breakfast: "Breakfast",
  mid_morning_snack: "Mid-Morning Snack",
  lunch: "Lunch",
  afternoon_snack: "Afternoon Snack",
  dinner: "Dinner",
  evening_snack: "Evening Snack",
};

export const generateAndDownloadPDF = (
  plan: any,
  userData: any,
  shoppingList: string[],
  setToast: (toast: any) => void
) => {
  try {
    const doc = new jsPDF();
    const margin = 14;
    let yPos = 20;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text("Your Personalized Fitness Plan", margin, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by Fitness AI | Goal: ${userData?.goal}`, margin, yPos);
    yPos += 15;

    // --- SAFETY WARNINGS (Critical) ---
    if (plan.safety_warnings && plan.safety_warnings.length > 0) {
      doc.setFillColor(255, 235, 235);
      doc.rect(margin, yPos, 180, 12 + plan.safety_warnings.length * 6, "F");

      doc.setFontSize(12);
      doc.setTextColor(200, 0, 0);
      doc.setFont("helvetica", "bold");
      doc.text("⚠️ SAFETY WARNINGS", margin + 5, yPos + 7);

      doc.setFontSize(9);
      doc.setTextColor(50);
      doc.setFont("helvetica", "normal");
      let warnY = yPos + 14;
      plan.safety_warnings.forEach((w: string) => {
        const lines = doc.splitTextToSize(`• ${w}`, 170);
        lines.forEach((line: string) => {
          doc.text(line, margin + 5, warnY);
          warnY += 5;
        });
      });
      yPos = warnY + 10;
    }

    // --- HEALTH CONSIDERATIONS ---
    if (plan.health_considerations) {
      if (yPos > 240) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFillColor(250, 240, 230);
      doc.rect(margin, yPos, 180, 35, "F");

      doc.setFontSize(12);
      doc.setTextColor(200, 100, 0);
      doc.setFont("helvetica", "bold");
      doc.text("🏥 Health Considerations", margin + 5, yPos + 7);

      doc.setFontSize(9);
      doc.setTextColor(50);
      doc.setFont("helvetica", "normal");
      let healthY = yPos + 14;

      if (plan.health_considerations.modifications) {
        doc.setFont("helvetica", "bold");
        doc.text("Modifications:", margin + 5, healthY);
        healthY += 5;
        doc.setFont("helvetica", "normal");
        const modLines = doc.splitTextToSize(
          plan.health_considerations.modifications,
          170
        );
        modLines.forEach((line: string) => {
          doc.text(line, margin + 5, healthY);
          healthY += 4;
        });
      }

      if (plan.health_considerations.red_flags) {
        healthY += 2;
        doc.setFont("helvetica", "bold");
        doc.text("Red Flags:", margin + 5, healthY);
        healthY += 5;
        doc.setFont("helvetica", "normal");
        const flagLines = doc.splitTextToSize(
          plan.health_considerations.red_flags,
          170
        );
        flagLines.forEach((line: string) => {
          doc.text(line, margin + 5, healthY);
          healthY += 4;
        });
      }

      yPos = healthY + 10;
    }

    // --- TIMELINE ---
    if (plan.results_timeline) {
      if (yPos > 240) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFontSize(14);
      doc.setTextColor(0);
      doc.setFont("helvetica", "bold");
      doc.text("📅 Projected Timeline", margin, yPos);
      yPos += 7;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(
        `Expected Start: ${plan.results_timeline.estimated_start}`,
        margin,
        yPos
      );
      yPos += 6;
      if (plan.results_timeline.milestones) {
        plan.results_timeline.milestones.forEach((m: string) => {
          const lines = doc.splitTextToSize(`• ${m}`, 180);
          lines.forEach((line: string) => {
            doc.text(line, margin, yPos);
            yPos += 5;
          });
        });
      }
      yPos += 10;
    }

    // --- HYDRATION & RECOVERY ---
    if (plan.hydration || plan.recovery) {
      if (yPos > 230) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("💧 Hydration & Recovery", margin, yPos);
      yPos += 8;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");

      if (plan.hydration) {
        doc.text(`Water Target: ${plan.hydration.target}`, margin, yPos);
        yPos += 6;
        if (plan.hydration.timing) {
          const timingLines = doc.splitTextToSize(
            `Timing: ${plan.hydration.timing}`,
            180
          );
          timingLines.forEach((line: string) => {
            doc.text(line, margin, yPos);
            yPos += 5;
          });
        }
      }
      if (plan.recovery) {
        yPos += 2;
        doc.text(`Sleep Target: ${plan.recovery.sleep_target}`, margin, yPos);
        yPos += 6;
        doc.text(`Rest Days: ${plan.recovery.rest_days}`, margin, yPos);
        yPos += 6;
        if (plan.recovery.stress_management) {
          const stressLines = doc.splitTextToSize(
            `Stress Management: ${plan.recovery.stress_management}`,
            180
          );
          stressLines.forEach((line: string) => {
            doc.text(line, margin, yPos);
            yPos += 5;
          });
        }
      }
      yPos += 10;
    }

    // --- WORKOUT ---
    const hasWorkout = plan.workout && Array.isArray(plan.workout);
    if (hasWorkout) {
      if (yPos > 220) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("💪 Weekly Workout Routine", margin, yPos);
      yPos += 8;

      const workoutRows = plan.workout.map((day: any) => {
        const exercises = day.exercises
          .map((ex: any) => {
            let txt = `• ${ex.name} (${ex.sets}x${ex.reps}, Rest: ${ex.rest})`;
            if (ex.modification) txt += `\n  [Modified: ${ex.modification}]`;
            return txt;
          })
          .join("\n");
        return [
          day.day,
          `${day.focus}\n${day.duration || ""}\n${day.intensity || ""}`,
          exercises,
        ];
      });

      autoTable(doc, {
        startY: yPos,
        head: [["Day", "Focus", "Exercises"]],
        body: workoutRows,
        theme: "grid",
        styles: { fontSize: 8, cellPadding: 3 },
        columnStyles: {
          0: { cellWidth: 25 },
          1: { cellWidth: 40 },
          2: { cellWidth: 115 },
        },
      });
      yPos = (doc as any).lastAutoTable.finalY + 15;
    }

    // --- DIET & NUTRITION ---
    if (plan.diet && plan.diet.meals) {
      if (yPos > 200) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("🍽️ Nutrition Plan", margin, yPos);
      yPos += 8;

      // Calorie Target
      if (plan.diet.calorie_target) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.text(
          `Daily Target: ${plan.diet.calorie_target.daily}`,
          margin,
          yPos
        );
        yPos += 5;
        if (plan.diet.calorie_target.explanation) {
          const expLines = doc.splitTextToSize(
            plan.diet.calorie_target.explanation,
            180
          );
          expLines.forEach((line: string) => {
            doc.text(line, margin, yPos);
            yPos += 4;
          });
        }
        yPos += 8;
      }

      // Macros
      if (plan.diet.macros) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text(
          `Macros: Protein: ${plan.diet.macros.protein}, Carbs: ${plan.diet.macros.carbs}, Fats: ${plan.diet.macros.fats}`,
          margin,
          yPos
        );
        yPos += 10;
      }

      // Meals Table
      const dietRows = MEAL_ORDER.filter((k) => plan.diet.meals[k]).map((k) => {
        const m = plan.diet.meals[k];
        const allergyNote =
          m.allergy_safe === "No" ? "\n⚠️ Contains allergen" : "";
        return [
          MEAL_LABELS[k] || k.toUpperCase(),
          `${m.meal}\n${m.portion || ""}${allergyNote}`,
          `${m.calories}kcal\nP:${m.protein} C:${m.carbs} F:${m.fats}`,
        ];
      });

      autoTable(doc, {
        startY: yPos,
        head: [["Meal", "Details", "Macros"]],
        body: dietRows,
        theme: "grid",
        styles: { fontSize: 8, cellPadding: 3 },
        columnStyles: {
          0: { cellWidth: 40 },
          1: { cellWidth: 100 },
          2: { cellWidth: 40 },
        },
      });
      yPos = (doc as any).lastAutoTable.finalY + 15;
    }

    // --- DIET STRATEGY ---
    if (plan.diet && plan.diet.strategy) {
      if (yPos > 220) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("📊 Diet Strategy", margin, yPos);
      yPos += 8;
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");

      if (plan.diet.strategy.week_1) {
        doc.setFont("helvetica", "bold");
        doc.text("Week 1:", margin, yPos);
        yPos += 5;
        doc.setFont("helvetica", "normal");
        const w1Lines = doc.splitTextToSize(plan.diet.strategy.week_1, 180);
        w1Lines.forEach((line: string) => {
          doc.text(line, margin, yPos);
          yPos += 4;
        });
        yPos += 3;
      }

      if (plan.diet.strategy.week_2) {
        doc.setFont("helvetica", "bold");
        doc.text("Week 2:", margin, yPos);
        yPos += 5;
        doc.setFont("helvetica", "normal");
        const w2Lines = doc.splitTextToSize(plan.diet.strategy.week_2, 180);
        w2Lines.forEach((line: string) => {
          doc.text(line, margin, yPos);
          yPos += 4;
        });
        yPos += 3;
      }

      if (plan.diet.strategy.week_3_4) {
        doc.setFont("helvetica", "bold");
        doc.text("Week 3-4:", margin, yPos);
        yPos += 5;
        doc.setFont("helvetica", "normal");
        const w34Lines = doc.splitTextToSize(plan.diet.strategy.week_3_4, 180);
        w34Lines.forEach((line: string) => {
          doc.text(line, margin, yPos);
          yPos += 4;
        });
        yPos += 3;
      }

      if (plan.diet.strategy.allergy_notes) {
        doc.setFont("helvetica", "bold");
        doc.text("⚠️ Allergy Notes:", margin, yPos);
        yPos += 5;
        doc.setFont("helvetica", "normal");
        const allergyLines = doc.splitTextToSize(
          plan.diet.strategy.allergy_notes,
          180
        );
        allergyLines.forEach((line: string) => {
          doc.text(line, margin, yPos);
          yPos += 4;
        });
      }

      yPos += 10;
    }

    // --- SUPPLEMENTS ---
    if (plan.supplements && plan.supplements.length > 0) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("💊 Recommended Supplements", margin, yPos);
      yPos += 8;
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");

      plan.supplements.forEach((supp: string) => {
        const suppLines = doc.splitTextToSize(`• ${supp}`, 180);
        suppLines.forEach((line: string) => {
          doc.text(line, margin, yPos);
          yPos += 5;
        });
      });
      yPos += 10;
    }

    // --- PROGRESS TRACKING ---
    if (plan.progress_tracking) {
      if (yPos > 220) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("📈 Progress Tracking", margin, yPos);
      yPos += 8;
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");

      if (plan.progress_tracking.measurements) {
        doc.setFont("helvetica", "bold");
        doc.text("Measurements:", margin, yPos);
        yPos += 5;
        doc.setFont("helvetica", "normal");
        plan.progress_tracking.measurements.forEach((m: string) => {
          doc.text(`• ${m}`, margin + 5, yPos);
          yPos += 4;
        });
        yPos += 3;
      }

      if (plan.progress_tracking.performance) {
        doc.setFont("helvetica", "bold");
        doc.text("Performance:", margin, yPos);
        yPos += 5;
        doc.setFont("helvetica", "normal");
        plan.progress_tracking.performance.forEach((p: string) => {
          doc.text(`• ${p}`, margin + 5, yPos);
          yPos += 4;
        });
        yPos += 3;
      }

      if (plan.progress_tracking.health_metrics) {
        doc.setFont("helvetica", "bold");
        doc.text("Health Metrics:", margin, yPos);
        yPos += 5;
        doc.setFont("helvetica", "normal");
        plan.progress_tracking.health_metrics.forEach((h: string) => {
          doc.text(`• ${h}`, margin + 5, yPos);
          yPos += 4;
        });
      }
    }

    // --- METADATA ---
    doc.addPage();
    yPos = 20;
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Plan Generated By:", margin, yPos);
    yPos += 6;
    doc.setFontSize(8);
    if (plan._metadata) {
      doc.text(`Provider: ${plan._metadata.provider}`, margin, yPos);
      yPos += 5;
      doc.text(`BMI: ${plan._metadata.bmi}`, margin, yPos);
      yPos += 5;
      doc.text(`BMR: ${plan._metadata.bmr} kcal/day`, margin, yPos);
      yPos += 5;
      doc.text(`TDEE: ${plan._metadata.tdee} kcal/day`, margin, yPos);
      yPos += 5;
      doc.text(
        `Health Factors Considered: ${plan._metadata.healthFactorsConsidered}`,
        margin,
        yPos
      );
      yPos += 5;
      doc.text(
        `Generated: ${new Date(plan._metadata.generatedAt).toLocaleString()}`,
        margin,
        yPos
      );
    }

    doc.save("Fitness_Plan.pdf");
    setToast({ show: true, message: "✅ Downloaded!", type: "success" });
  } catch (error) {
    console.error(error);
    setToast({ show: true, message: "❌ Export failed.", type: "error" });
  }
};
